# Generated by Django 6.0.3 on 2026-03-31 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('illustration_url', models.URLField(blank=True)),
                ('intro', models.TextField()),
                ('objectives', models.TextField(help_text='Une ligne par objectif pedagogique.')),
                ('content', models.TextField(help_text='Corps principal de l article.')),
                ('conclusion', models.TextField()),
                ('reflection_questions', models.TextField(help_text='Une ligne par question de reflexion.')),
                ('resources', models.TextField(blank=True, help_text='Une ligne par ressource supplementaire.')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publie')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='blog.tag')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=32)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('session_id', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='blog.article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reads', models.PositiveIntegerField(default=0)),
                ('total_seconds_read', models.PositiveIntegerField(default=0)),
                ('intro_seconds', models.PositiveIntegerField(default=0)),
                ('objectives_seconds', models.PositiveIntegerField(default=0)),
                ('content_seconds', models.PositiveIntegerField(default=0)),
                ('conclusion_seconds', models.PositiveIntegerField(default=0)),
                ('resources_seconds', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='blog.article')),
            ],
        ),
        migrations.CreateModel(
            name='ReaderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Lecteur', max_length=120)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.article')),
            ],
        ),
    ]
