# Generated by Django 6.0.3 on 2026-04-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_actionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='audio_upload',
            field=models.FileField(blank=True, null=True, upload_to='articles/audio/'),
        ),
        migrations.AddField(
            model_name='article',
            name='audio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='enable_analytics',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='article',
            name='illustration_upload',
            field=models.FileField(blank=True, null=True, upload_to='articles/images/'),
        ),
        migrations.AddField(
            model_name='article',
            name='video_upload',
            field=models.FileField(blank=True, null=True, upload_to='articles/videos/'),
        ),
        migrations.AddField(
            model_name='article',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
