# Generated by Django 6.0.3 on 2026-04-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_media_and_analytics_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('histoires_contes', 'Histoires courtes et contes'), ('defis_reflexion', 'Défis de réflexion'), ('decouverte_monde', 'Découverte du monde'), ('sciences_amusantes', 'Sciences amusantes'), ('maths_ludiques', 'Mathématiques ludiques'), ('apprentissage_mots', 'Apprentissage des mots'), ('activites_creatives', 'Activités créatives'), ('vie_quotidienne', 'Histoires de la vie quotidienne'), ('valeurs_comportements', 'Valeurs et comportements'), ('animaux_nature', 'Animaux et nature'), ('histoire_simplifiee', 'Histoire simplifiée'), ('initiation_numerique', 'Initiation au numérique'), ('jeux_role_imagination', 'Jeux de rôle et imagination'), ('jeux_educatifs', 'Jeux éducatifs interactifs'), ('comptines_chansons', 'Comptines et chansons'), ('metiers_reves', 'Métiers et rêves'), ('ecologie_environnement', 'Écologie et environnement'), ('emotions_bienetre', 'Émotions et bien-être'), ('langues_communication', 'Langues et communication'), ('histoires_interactives', 'Histoires interactives')], db_index=True, help_text="Catégorie principale de l'article.", max_length=40),
        ),
    ]
