# Generated by Django 6.0.3 on 2026-04-06 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_add_category_to_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='readercomment',
            name='email',
            field=models.EmailField(blank=True, help_text='Optionnel — non publié', max_length=254),
        ),
        migrations.AddField(
            model_name='readercomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.readercomment'),
        ),
        migrations.AlterField(
            model_name='readercomment',
            name='message',
            field=models.TextField(max_length=1000),
        ),
    ]
