# Generated by Django 6.0.3 on 2026-04-03 14:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_article_id', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('client_user_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reads', models.PositiveIntegerField(default=0)),
                ('total_seconds_read', models.PositiveIntegerField(default=0)),
                ('intro_seconds', models.PositiveIntegerField(default=0)),
                ('objectives_seconds', models.PositiveIntegerField(default=0)),
                ('content_seconds', models.PositiveIntegerField(default=0)),
                ('conclusion_seconds', models.PositiveIntegerField(default=0)),
                ('resources_seconds', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='analytics.article')),
            ],
        ),
        migrations.CreateModel(
            name='RawEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('analytics', 'Analytics'), ('action_log', 'Action Log')], max_length=20)),
                ('section', models.CharField(blank=True, max_length=64)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('session_id', models.CharField(blank=True, max_length=80)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('browser', models.CharField(blank=True, max_length=40)),
                ('action', models.CharField(blank=True, max_length=80)),
                ('actor_type', models.CharField(blank=True, max_length=20)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_events', to='analytics.article')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_events', to='analytics.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='analytics.teacher'),
        ),
        migrations.CreateModel(
            name='DailyReads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reads', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reads', to='analytics.article')),
            ],
            options={
                'unique_together': {('article', 'date')},
            },
        ),
    ]
