# Generated by Django 6.0.3 on 2026-04-08 11:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('category', models.CharField(blank=True, max_length=40)),
                ('intro', models.TextField(blank=True)),
                ('objectives', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('reflection_questions', models.TextField(blank=True)),
                ('resources', models.TextField(blank=True)),
                ('illustration_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('audio_url', models.URLField(blank=True)),
                ('enable_analytics', models.BooleanField(default=True)),
                ('status', models.CharField(default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'client_article',
            },
        ),
        migrations.CreateModel(
            name='ClientTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=90)),
            ],
            options={
                'db_table': 'client_tag',
            },
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.PositiveIntegerField(help_text='PK in the client database', unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'client_user',
            },
        ),
        migrations.CreateModel(
            name='ClientAnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.PositiveIntegerField(unique=True)),
                ('section', models.CharField(max_length=32)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('session_id', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='analytics.clientarticle')),
            ],
            options={
                'db_table': 'client_analyticsevent',
            },
        ),
        migrations.CreateModel(
            name='ClientArticleAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.PositiveIntegerField(unique=True)),
                ('total_reads', models.PositiveIntegerField(default=0)),
                ('total_seconds_read', models.PositiveIntegerField(default=0)),
                ('intro_seconds', models.PositiveIntegerField(default=0)),
                ('objectives_seconds', models.PositiveIntegerField(default=0)),
                ('content_seconds', models.PositiveIntegerField(default=0)),
                ('conclusion_seconds', models.PositiveIntegerField(default=0)),
                ('resources_seconds', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='analytics.clientarticle')),
            ],
            options={
                'db_table': 'client_articleanalytics',
            },
        ),
        migrations.AddField(
            model_name='clientarticle',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='analytics.clienttag'),
        ),
        migrations.AddField(
            model_name='clientarticle',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='analytics.clientuser'),
        ),
        migrations.CreateModel(
            name='ClientActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.PositiveIntegerField(unique=True)),
                ('action', models.CharField(max_length=80)),
                ('actor_type', models.CharField(default='anonymous', max_length=16)),
                ('request_path', models.CharField(blank=True, max_length=250)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('session_id', models.CharField(blank=True, max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='analytics.clientarticle')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='analytics.clientuser')),
            ],
            options={
                'db_table': 'client_actionlog',
            },
        ),
        migrations.CreateModel(
            name='ClientReaderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(default='Lecteur', max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField()),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='analytics.clientarticle')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='analytics.clientreadercomment')),
            ],
            options={
                'db_table': 'client_readercomment',
                'indexes': [models.Index(fields=['article', 'is_approved'], name='client_read_article_f144e0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='clientarticle',
            index=models.Index(fields=['status', 'published_at'], name='client_arti_status_2cdc08_idx'),
        ),
        migrations.AddIndex(
            model_name='clientarticle',
            index=models.Index(fields=['author', 'status'], name='client_arti_author__de721a_idx'),
        ),
        migrations.AddIndex(
            model_name='clientarticle',
            index=models.Index(fields=['category'], name='client_arti_categor_6cb805_idx'),
        ),
        migrations.AddIndex(
            model_name='clientactionlog',
            index=models.Index(fields=['action', 'created_at'], name='client_acti_action_52830f_idx'),
        ),
        migrations.AddIndex(
            model_name='clientactionlog',
            index=models.Index(fields=['article', 'action'], name='client_acti_article_36e91e_idx'),
        ),
        migrations.AddIndex(
            model_name='clientactionlog',
            index=models.Index(fields=['user', 'action'], name='client_acti_user_id_730493_idx'),
        ),
    ]
